version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_ROOT}/postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:6-alpine

  nextcloud:
    restart: always
    image: nextcloud:21-apache
    volumes:
      - ${DATA_ROOT}/nextcloud/html:/var/www/html
      - ${DATA_ROOT}/nextcloud/data:/var/www/html/data
      - ${DATA_ROOT}/nextcloud/config:/var/www/html/config
      - ${DATA_ROOT}/nextcloud/custom_apps:/var/www/html/custom_apps
    depends_on: [postgres, redis]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis

  acme:
    restart: always
    build:
      context: ./acme
    volumes:
      - ${DATA_ROOT}/acme.sh:/acme.sh
      - ${DATA_ROOT}/ssl:/ssl
      - ${DATA_ROOT}/acme-challenge:/acme-challenge
    environment:
      DOMAINS: ${DOMAINS}

  proxy:
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${DATA_ROOT}/ssl:/etc/nginx/ssl
      - ${DATA_ROOT}/acme-challenge:/acme-challenge
    depends_on: [nextcloud, acme]
    ports:
      - "80:80"
      - "443:443"
